blank_issues_enabled: false
contact_links:
  - name: 💡 General Questions & Discussions
    url: https://github.com/JimmyJammed/govee-lan-api-plus/discussions
    about: Use GitHub Discussions for general Q&A and brainstorming ideas.